export const permissionSetsFolder = "permissionSets";
export const permissionSetFileEnd = "permissionSet.al";
export const defaultPermissionSetName = "Permission";
export const permissionTable = "rimd";
export const permissionExecute = "x";
export const permissionFileCreated = "Permission set file has been created successfully.";
export const permissionObjectTypeRegEx = /\b(CODEUNIT|PAGE|TABLE|REPORT|XMLPORT)\b/i;
export const permissionReadWriteObjectTypeRegEx = /\b(TABLE)\b/i;
export const permissionNewLine = ",\n\t\t";
